<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Holdus.API</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- JWT Authentication -->
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.*" />

    <!-- Swagger -->
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.*" />

    <!-- Hangfire Dashboard -->
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.*" />

    <!-- Redis Cache -->
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.*" />

    <!-- Health Checks -->
    <PackageReference Include="AspNetCore.HealthChecks.Npgsql" Version="9.*" />
    <PackageReference Include="AspNetCore.HealthChecks.Redis" Version="9.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Holdus.Application\Holdus.Application.csproj" />
  </ItemGroup>
</Project>
